create table bids (
  id bigint generated by default as identity primary key,
  amount integer not null,
  auction_id bigint references public.auctions not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

alter table bids enable row level security;

create policy "Individuals can create bids." on bids for
    insert with check (auth.uid() = user_id);

-- create policy "Individuals can update their own bids." on bids for
--     update using (auth.uid() = user_id);

-- create policy "Individuals can delete their own bids." on bids for
--     delete using (auth.uid() = user_id);

create policy "Bids are public." on bids for
    select using (true);
