-- Set up table
create table watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  auction_id bigint references public.auctions not null,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set row level security
alter table bids enable row level security;

create policy "Users can select their watches."
  on watchlist
  for select using (
    (auth.uid() = user_id)
  );

create policy "Users can create a watch."
  on watchlist
  for insert with check (
    (auth.uid() = user_id)
  );

create policy "Users can delete their own watch."
  on watchlist
  for delete using (
    auth.uid() = user_id
  );

-- Enable replication for realtime
-- Requires full as we want to listen for deletes too
alter table watchlist replica identity full;
